### ISSUE TITLE
Regarding the calculation of tau

### ISSUE THREAD

**Issue by ravindraji4** [groundstate/tftools#1]
Hello Mr. Wouters, 
Thank you very much for valuable knowledge and the source code without restrictions. 
I would like to ask how to calculate the tau in case if I have for example 200 values with the frequency of 125 Hz. 
I tried the same file, but it didn't evaluate any results and break/skip out of the for loop instead. 
Thank you very much in advance.

**Comment by groundstate** [comment]
Hello,
Thanks for your feedback.

When reporting a possible bug, the best information you can give is an example of the Matlab code that is failing. I can then very quickly identify the problem .

Here is an example of calculating overlapping ADEV for phase data sampled at 125 Hz with no gaps:
sample_rate=125.0;
x=rand(1,200);
tau = [1 2 5 10 20 50 70]/sample_rate;
[ dev, deverr, ndev, new_tau ] = adev(x,sample_rate,tau,1,1,0) ;
loglog(new_tau, dev, '+-')

**Comment by groundstate** [comment]
No feedback received so closing this since it is not evident that there is a bug.
